name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Date
        run: |
          echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_ENV

      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.date }}-
            ${{ runner.os }}-

      - name: Install Buildozer
        run: |
          pip install buildozer

      - name: Install Python Dependencies
        run: |
          pip install kivy==2.2.1 pyjnius==1.5.0 pillow numpy plyer cython==0.29.33

      - name: Build with Buildozer
        run: |
          buildozer init
          buildozer android debug  # Adjust the buildozer command as needed for your project

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: .buildozer/bin  # Adjust the path to match your buildozer output directory
